### ISSUE TITLE
StyleGuide project fails to build

### ISSUE THREAD

**Issue by nwinger** [heartbeatua/Pulse-Boilerplate#1]
Yarn dev appears to be working, but yarn guide breaks with the following error:
![image](https://user-images.githubusercontent.com/859037/53621699-a56f3380-3bf7-11e9-9931-9cdffdb18373.png)

**Comment by nwinger** [comment]
@butafor Any suggestions? :)

**Comment by butafor** [comment]
@nwinger 
We apologize for the long response. We prepared a big update with a lot of fixes and improvements.
Could you find the time and check if everything works this time?

**Comment by nwinger** [comment]
Works now! 🎉🎉|
