### ISSUE TITLE
Installable Component Library

### ISSUE THREAD

**Issue by elbakerino** [heartbeatua/Pulse-Boilerplate#5]
Hey there!

I really like the radical simplicity of pulse, is there an installable component library or only this boilerplate?

With installable I mean like [MUI](https://material-ui.com/) or [AntD](https://ant.design/docs/react/introduce), which can simply be added to a project and not where the project must be based on this boilerplate.

Would like to add a binding to .pulse in [UI-Schema](https://github.com/ui-schema/ui-schema), but if i need to use the boilerplate, it's more like reimplementing the boilerplate instead of using ready components.

Cheers!

**Comment by butafor** [comment]
Hey @elbakerino 

No, this is not an installable library. It just only a boilerplate for now.

**Comment by elbakerino** [comment]
Thanks for the info!

After further checking, sadly to much effort.
